"""Create client table

Revision ID: 196ac29f1c21
Revises: 
Create Date: 2024-04-07 13:54:06.622837+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '196ac29f1c21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('public_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_salt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_version', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('client_type', sa.Enum('Webhook', name='clienttype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
